### ISSUE TITLE
OCast-Java not compatible with Android 10 devices?

### ISSUE THREAD

**Issue by LeDanielH** [Orange-OpenSource/OCast-JVM#83]
Hello,

we are still using deprecated version of your package: https://github.com/Orange-OpenSource/OCast-Java but I cannot report an issue there since it is deprecated.

Is it possible, that the deprecated package is not compatible with Android 10? E.g. I already had to update the way we connect to OCast stick, because our code was incompatible with Android 10. 

I can connect to it as I would connect to any other wifi from our app. But I cannot start pairing.

To be specific, `public void onDeviceAdded(DiscoveredDevice device)` from `org.ocast.discovery.Discovery` does not get triggered, when I try to pair Android 10 device. 

I will be fine with "you need to upgrade to non deprecated version" kind of response. At least we will be forced to upgrade to non deprecated version as soon as possible.

Best Regards
Daniel

**Comment by ttassain** [comment]
Hello,

Devices discover use HTTP (non SSL) , add this line to your `AndroidManifest.xml`

```
<application
        android:usesCleartextTraffic="true"
```
